const carriers = [
  {
    name: "Advantage",
    email: "",
    link: "https://customer.advantageauto.com/diamondweb/(S(5t3oybd5dvy3lib2bao0s5eo))/consumer",
    phone: "1 (800) 422-0792",
    phone2: "",
    note: "",
    logo: "images/advantage.png",
  },
  {
    name: "American Home Shield",
    email: "",
    link: "https://www.ahs.com/",
    phone: "1 (800) 858-1922",
    phone2: "",
    note: "",
    logo: "images/ahs.png",
  },
  {
    name: "AMWins",
    email: "",
    link: "https://www.amwins.com/",
    phone: "",
    phone2: "",
    note: "",
    logo: "images/amwins.png",
  },
  {
    name: "Atrium",
    email: "",
    link: "https://www.atriuminsurancegroup.com/",
    phone: "1 (303) 337-4433",
    phone2: "",
    note: "",
    logo: "images/atrium.png",
  },
  {
    name: "Bristol West",
    email: "",
    link: "https://www.bristolwest.com/",
    phone: "1 (800) 274-7865",
    phone2: "",
    note: "",
    logo: "images/bristol.png",
  },
  {
    name: "BTIS",
    email: "",
    link: "https://my.btisinc.com/",
    phone: "	1 (877) 649-6682",
    phone2: "",
    note: "",
    logo: "images/btis.png",
  },
  {
    name: "Burns & Wilcox",
    email: "",
    link: "https://www.burnsandwilcox.com/",
    phone: " 1 (303) 804-0200",
    phone2: "",
    note: "",
    logo: "images/burnswilcox.png",
  },
  {
    name: "Bond Exchange",
    email: "",
    link: "https://www.bondexchange.com/",
    phone: "1 (800) 438-1162",
    phone2: "",
    note: "",
    logo: "images/bx.png",
  },
  {
    name: "Capital",
    email: "",
    link: "https://www.capitalpremium.net/payment-options/",
    phone: "1 (800) 767-0705",
    phone2: "",
    note: "",
    logo: "images/capital.png",
  },
  {
    name: "CharityFirst",
    email: "",
    link: "https://www.charityfirst.com/",
    phone: "1 (800) 352-2761",
    phone2: "",
    note: "",
    logo: "images/charity.png",
  },
  {
    name: "Chubb",
    email: "",
    link: "https://www.chubb.com/us-en/",
    phone: "1 (800) 252-4670",
    phone2: "",
    note: "",
    logo: "images/chubb.png",
  },
  {
    name: "CNA",
    email: "",
    link: "https://www.cna.com/web/guest/cna/home",
    phone: "1 (877) 574-0540",
    phone2: "",
    note: "",
    logo: "images/cna.png",
  },
  {
    name: "Colonial General",
    email: "",
    link: "https://www.colonialgeneral.com/",
    phone: "1 (800) 848-8860",
    phone2: "",
    note: "",
    logo: "images/colonial.png",
  },
  {
    name: "CRC Group",
    email: "",
    link: "https://www.crcgroup.com/",
    phone: "",
    phone2: "",
    note: "",
    logo: "images/crc.png",
  },
  {
    name: "Distinguished Programs",
    email: "",
    link: "https://distinguished.com/",
    phone: "1 (212) 297-3100",
    phone2: "",
    note: "",
    logo: "images/distinguished.png",
  },
  {
    name: "EverGuard",
    email: "",
    link: "https://everguardins.com/",
    phone: "1 (800) 326-8514",
    phone2: "",
    note: "",
    logo: "images/everguard.png",
  },
  {
    name: "Francis L. Dean",
    email: "",
    link: "https://fdean.com/",
    phone: "1 (800) 745-2409",
    phone2: "",
    note: "",
    logo: "images/fldean.png",
  },
  {
    name: "Foremost",
    email: "",
    link: "https://www.myforemostaccount.com/login",
    phone: "1 (800) 527-3907",
    phone2: "",
    note: "",
    logo: "images/foremost.png",
  },
  {
    name: "The General",
    email: "Claims@thegeneral.com",
    link: "https://www.thegeneral.com/mypolicy/welcome.htm",
    phone: "1 (800) 280-1466",
    phone2: "",
    note: "",
    logo: "images/general.png",
  },
  {
    name: "Hagerty",
    email: "",
    link: "https://login.hagerty.com/identity/login?ReturnUrl=%2F",
    phone: "1 (800) 385-0274",
    phone2: "",
    note: "",
    logo: "images/hagerty.png",
  },
  {
    name: "The Hartford",
    email: "",
    link: "https://account.thehartford.com/customer/#/login?appid=OBSC&goto=https%3A%2F%2Fbusiness.thehartford.com%3A443%2Fpolicies",
    phone: "1 (866) 467-8730",
    phone2: "",
    note: "",
    logo: "images/hartford.png",
  },
  {
    name: "Hiscox",
    email: "",
    link: "https://www.hiscox.com/small-business-insurance-lp?medium=tsa&_vsrefdom=2018031503&leadorigin=SEM_Brand_Google&gad=1&gclid=CjwKCAjw-7OlBhB8EiwAnoOEk27HeGSyycIjGgdyisOGZcPg9aWIstXK465BpYUHzLb-rkgAaunFyxoCzHUQAvD_BwE&gclsrc=aw.ds",
    phone: "",
    phone2: "1 (855) 928-6183",
    note: "",
    logo: "images/hiscox.png",
  },
  {
    name: "J.C. Taylor",
    email: "",
    link: "https://jctaylor.com/",
    phone: "1 (800) 345-8290",
    phone2: "",
    note: "",
    logo: "images/jctaylor.png",
  },
  {
    name: "Kemper",
    email: "",
    link: "https://www.kemper.com/",
    phone: "1 (866) 536-7376",
    phone2: "1 (888) 252-2799",
    note: "",
    logo: "images/kemper.png",
  },
  {
    name: "Liberty Mutual",
    email: "",
    link: "https://business.libertymutual.com/login/",
    phone: "1 (844) 325-2467",
    phone2: "1 (800) 362-0000",
    note: "Mid-Lage Size Customers",
    logo: "images/libertymutual.png",
  },
  {
    name: "Markel",
    email: "",
    link: "https://www.markel.com/",
    phone: "1 (800) 446-6671",
    phone2: "1 (800 362-7535",
    note: "emergencies",
    logo: "images/markel.png",
  },
  {
    name: "MarketScout",
    email: "",
    link: "https://marketscout.com/",
    phone: "1 (972) 934-4200",
    phone2: "",
    note: "",
    logo: "images/marketscout.png",
  },
  {
    name: "Mendota",
    email: "",
    link: "https://customer.advantageauto.com/diamondweb/(S(5t3oybd5dvy3lib2bao0s5eo))/consumer",
    phone: "1 (800) 422-0792",
    phone2: "",
    note: "",
    logo: "images/mendota.png",
  },
  {
    name: "MetLife",
    email: "",
    link: "https://www.metlife.com/",
    phone: "1 (800) 638-5433",
    phone2: "",
    note: "",
    logo: "images/metlife.png",
  },
  {
    name: "National General",
    email: "",
    link: "https://nationalgeneral.com/",
    phone: " 1 (800) 468-3466",
    phone2: "",
    note: "",
    logo: "images/nationalgeneral.png",
  },
  {
    name: "Nationwide",
    email: "",
    link: "https://www.nationwide.com/account-login",
    phone: "1 (800) 421-3535",
    phone2: "1 (866) 854-4140",
    note: "Roadside Assistance",
    logo: "images/nationwide.png",
  },
  {
    name: "Next",
    email: "",
    link: "https://www.nextinsurance.com/",
    phone: "",
    phone2: "",
    note: "",
    logo: "images/next.png",
  },
  {
    name: "Personal Umbrella",
    email: "",
    link: "",
    phone: "",
    phone2: "",
    note: "Call Agent to File Claim",
    logo: "images/personalumbrella.png",
  },
  {
    name: "Philadelphia",
    email: "",
    link: "https://www.phly.com/Home/Index.aspx",
    phone: "1 (800) 765-9749",
    phone2: "",
    note: "",
    logo: "images/philadelphia.png",
  },
  {
    name: "Pinnacol",
    email: "",
    link: "https://policyholder.pinnacol.com/auth/users/sign_in",
    phone: "1 (303) 361-4000",
    phone2: "1 (800) 873-7242",
    note: "",
    logo: "images/pinnacol.png",
  },
  {
    name: "Progressive",
    email: "",
    link: "https://www.progressive.com/manage-policy/",
    phone: "1 (800) 776-4737",
    phone2: "1 (800) 776-2778",
    note: "Roadside Assistance",
    logo: "images/progressive.png",
  },
  {
    name: "RIC",
    email: "",
    link: "https://www.ric-ins.com/",
    phone: "1 (888) 693-7892",
    phone2: "",
    note: "",
    logo: "images/ric.png",
  },
  {
    name: "Ryan Turner",
    email: "",
    link: "https://rtspecialty.com/",
    phone: "",
    phone2: "",
    note: "",
    logo: "images/ryanturner.png",
  },
  {
    name: "Safeco",
    email: "",
    link: "https://login.safeco.com/login?state=hKFo2SB2Nm5DWlAxOVdXY1psUlp2YTlQR2lDYjA2c0RlbzAxYqFupWxvZ2luo3RpZNkgN0pjcnNXMkEwbzR2aHQ1ZnVKcGxlNnV2V25ZX0E2TjSjY2lk2SB3dTlvWnFlWVB4aUJpSVlYYms5M3NNdWJSOTFyZ3JxZw&client=wu9oZqeYPxiBiIYXbk93sMubR91rgrqg&protocol=oauth2&redirect_uri=https%3A%2F%2Fcustomer.safeco.com%2Faccountmanager%2F&audience=https%3A%2F%2Fcustomer.safeco.com%2Faccountmanager%2Fapi&scope=openid%20profile%20email%20offline_access&response_type=code&response_mode=query&nonce=aTdfZ0NPWkRNQmdYTGE5S1BNWEM0RzBJSDBTS2hUR3AtMmcyc25FZEV0eg%3D%3D&code_challenge=1af4ZPqHMeR4PxbPqPE3Ah0pLrSZcs4FPookN2yq30A&code_challenge_method=S256&auth0Client=eyJuYW1lIjoiQGF1dGgwL2F1dGgwLWFuZ3VsYXIiLCJ2ZXJzaW9uIjoiMS4xMS4xIiwiZW52Ijp7ImFuZ3VsYXIvY29yZSI6IjEzLjQuMCJ9fQ%3D%3D",
    phone: "1 (800) 332-3226",
    phone2: "",
    note: "",
    logo: "images/safeco.png",
  },
  {
    name: "Safeway",
    email: "",
    link: "https://www.mysafeway.com/default.aspx?Lang=EN",
    phone: "1 (888) 203-5129",
    phone2: "",
    note: "",
    logo: "images/safeway.png",
  },
  {
    name: "Scottsdale",
    email: "",
    link: "",
    phone: "",
    phone2: "",
    note: "",
    logo: "images/scottsdale.png",
  },
  {
    name: "Travelers",
    email: "",
    link: "https://www.travelers.com/login/#/",
    phone: "1 (800) 238-6225",
    phone2: "",
    note: "",
    logo: "images/travelers.png",
  },
  {
    name: "USLI",
    email: "",
    link: "https://www.usli.com/",
    phone: "1 (888) 523-5545",
    phone2: "",
    note: "",
    logo: "images/usli.png",
  },
  {
    name: "Virtus",
    email: "",
    link: "https://www.virtusinsurance.com/",
    phone: "",
    phone2: "",
    note: "",
    logo: "images/virtus.png",
  },
  {
    name: "Western Pacific",
    email: "",
    link: "https://westpacins.com/",
    phone: "1 (303) 904-3777",
    phone2: "",
    note: "",
    logo: "images/westernpacific.png",
  },
];

module.exports = carriers;
